### ISSUE TITLE
Latest docker hub image doesn't have a version tag

### ISSUE THREAD

**Issue by djeikyb** [eaudeweb/edw.docker.mailtrap#10]
When I browse to:

https://hub.docker.com/r/eaudeweb/mailtrap/tags

The most recent tag is "latest", with hash:

    f034cbf3dc1908aea42c1985d53697af07d7733ca4af6177b611437545ec7183

I expect there to be a version tag also. Is this a pre-release, or is the version tag just missing?

**Comment by alecghica** [comment]
The latest include this fix https://github.com/eaudeweb/edw.docker.mailtrap/commit/69b402d861dd493b9259ff7d4c55c54d34971753.

**Comment by alecghica** [comment]
The version tag is just missing, will be fixed soon.
